### ISSUE TITLE
Specify Proxy

### ISSUE THREAD

**Issue by binaryblake** [michaellavelle/spring-data-dynamodb-demo#5]
How can we specify a proxy that should be used on the request out to the dynamoDB endpoint?

**Comment by michaellavelle** [comment]
Hi

You should be able to configure a proxy by creating an instance of ClientConfiguration ( http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html ) and passing this as an argument to the AmazonDynamoDBClient constructor when it's called with the spring configuration config.

Hope this helps,

Michael

**Comment by binaryblake** [comment]
Yes, that worked perfectly. Thanks for the quick response!
